### ISSUE TITLE
How to ajust map height ? 

### ISSUE THREAD

**Issue by Doctor-Who** [foxfabi/grav-plugin-leaflet-address#3]
Hello,

First, thanks for that great plugin.
I'm using latest release with [Grav] v1.7.42.3 - Admin v1.10.42 , Helium theme and Gantry plugin.

When displaying my map by copying `
{% include "partials/leaflet-address-map.html.twig" with {'config': config.plugins['leaflet-address']} %}` in my page content.

The map is too huge : 1150 px height and even by adding some information such as : 

```css
.leaflet-container {
    height: 300px;
#leaflet-address-map {
    height: 300px;
}
```

It doesn't work.

Thanks for your help.
